# Generated by Django 3.1.2 on 2020-10-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='title',
        ),
    ]
