# Generated by Django 3.1.2 on 2020-10-21 20:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 20, 0, 9, 287568, tzinfo=utc)),
        ),
    ]
