# Generated by Django 3.1.2 on 2020-10-21 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0002_auto_20201021_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
