# Generated by Django 3.1.2 on 2020-10-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0002_remove_testmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
